# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Suresh_CodeTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Suresh_CodeTest

    pod 'Masonry'


  target 'Suresh_CodeTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Suresh_CodeTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
